export const GET_SLIDER_VALUE = "GET_SLIDER_VALUE";

export const SET_ARRAY_NUMS = "SET_ARRAY_NUMS";

export const SET_ANIMATION_SPEED = "SET_ANIMATION_SPEED";

export const SET_BAR_WIDTH_MARGIN = "SET_BAR_WIDTH_MARGIN";

export const MERGE_SORT = "MERGE_SORT";

export const BUBBLE_SORT = "BUBBLE_SORT";

export const QUICK_SORT = "QUICK_SORT";

export const SELECTION_SORT = "SELECTION_SORT";

export const INSERTION_SORT = "INSERTION_SORT";

export const SORT_END = "SORT_END";
